version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/node-texlive
          update-description: true
          use-docker-credentials-store: true
          filters:
            branches:
              only:
                - master

