version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          cache_from: etops/node-texlive:latest
          image: etops/node-texlive
          tag: latest,$CIRCLE_BUILD_NUM
          update-description: true
          use-docker-credentials-store: true
          filters:
            branches:
              only:
                - master

